Add Contributions by CroutonDigital
celestiaorg/awesome-celestia pull request #16
Opened 2024-07-02 15:06 UTC by romanv1812

Contributions by CroutonDigital for delegation program

2024-08-08 15:38 UTC, jcstein approved these changes

2024-08-08 16:04 UTC, jcstein commented
hi @romanv1812 i tried to resolve conflicts, but ran into issue with edit access:

```
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
ERROR: Permission to Crouton-Digital/awesome-celestia.git denied to jcstein.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

can you please resolve conflicts? thanks!

2024-08-09 07:58 UTC, romanv1812 commented
Hello @jcstein, conflicts resolved.

2024-08-09 10:36 UTC, CroutonDigital commented
> hi @romanv1812 i tried to resolve conflicts, but ran into issue with edit access:
> 
> ```
> Switched to branch 'main'
> Your branch is up to date with 'origin/main'.
> Already up to date.
> ERROR: Permission to Crouton-Digital/awesome-celestia.git denied to jcstein.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> can you please resolve conflicts? thanks!

@jcstein  I resolve access issue, can you try again? 

thanks!

2024-08-14 02:51 UTC, jcstein commented
every time a new PR is merged, conflicts will arise and I will still not have write access to resolve. can you please modify this PR so I have write access to modify it? thanks! then I'll resolve issues.

2024-08-15 05:56 UTC, CroutonDigital commented
@jcstein Thank you! 

I fixed and merge PR. Can you check? 

Thank you!

2024-08-21 15:49 UTC, jcstein requested changes

2024-08-21 15:49 UTC, jcstein commented on README.md
> +=======
```suggestion
```

this is from resolving conflicts

2024-08-21 15:49 UTC, jcstein commented on README.md
> -### Contributions by [Stakin](https://stakin.com)
why's this removed?

2024-08-21 15:50 UTC, jcstein commented
it will be easiest to open a PR and just put your contributions at the end of the list, with the same format as others. thanks!

2024-08-21 18:16 UTC, maximdogonov commented
I'm sorry, let try again fix my PR. 
Thank you!

2024-08-21 18:46 UTC, jcstein commented
no worries @maximdogonov !

2024-08-21 18:47 UTC, jcstein requested changes

2024-08-21 18:47 UTC, jcstein commented on README.md
> -### List of Contributions from [Encapsulate (fka KingSuper)](https://encapsulate.xyz/)
now it is removing kingsuper. please just reopen a new pr like https://github.com/celestiaorg/awesome-celestia/pull/65

2024-08-21 18:53 UTC, closed without merging