Add Stakin contributions
celestiaorg/awesome-celestia pull request #30
Opened 2024-07-05 06:15 UTC by geldmon

## Overview

2024-08-08 18:41 UTC, jcstein requested changes
hi @geldmon please resolve conflicts

2024-08-08 19:51 UTC, geldmon commented
:white_check_mark: @jcstein

2024-08-08 22:03 UTC, jcstein commented on README.md
> +######
```suggestion
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +######
```suggestion
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +### Mainnet:
```suggestion
#### Mainnet
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +##### Relayers: We support Celestia by providing relayers channels, this is our relayers wallet for Celestia
```suggestion
* Relayers: We support Celestia by providing relayers channels, this is our relayers wallet for Celestia 
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +#### RPC: https://celestia.rpc.stakin-nodes.com
```suggestion
* RPC: https://celestia.rpc.stakin-nodes.com
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +#### gRPC: celestia.grpc.stakin-nodes.com:443
```suggestion
* gRPC: celestia.grpc.stakin-nodes.com:443
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +#### API: https://celestia.rest.stakin-nodes.com
```suggestion
* API: https://celestia.rest.stakin-nodes.com
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +#### Dashboard and staking interface:
```suggestion
* Dashboard and staking interface: 
```

2024-08-08 22:04 UTC, jcstein commented on README.md
> +##### Blog/Articles: [https://stakin.com/blog/tag/celestia](https://stakin.com/blog/tag/celestia)
```suggestion
* Blog/Articles: [https://stakin.com/blog/tag/celestia](https://stakin.com/blog/tag/celestia)
```

2024-08-08 22:05 UTC, jcstein commented on README.md
> +### Testnet:
```suggestion
#### Testnet:
```

2024-08-08 22:05 UTC, jcstein commented on README.md
> +#### Validator: [celestiavaloper1wf5az63pmykhnevyjcja68wdgs7h8y4w565lha](https://testnet.celestia.explorers.guru/validator/celestiavaloper1wf5az63pmykhnevyjcja68wdgs7h8y4w565lha)
```suggestion
* Validator: [celestiavaloper1wf5az63pmykhnevyjcja68wdgs7h8y4w565lha](https://testnet.celestia.explorers.guru/validator/celestiavaloper1wf5az63pmykhnevyjcja68wdgs7h8y4w565lha)
```

2024-08-08 22:05 UTC, jcstein commented on README.md
> +##### Bridge:
```suggestion
* Bridge: 
```

2024-08-08 22:05 UTC, jcstein commented on README.md
> +
```suggestion
```

2024-08-08 22:05 UTC, jcstein commented on README.md
> +
```suggestion
```

2024-08-08 22:22 UTC, jcstein commented
please apply changes so it fits current format. thanks!

2024-08-09 17:46 UTC, geldmon commented
✅  @jcstein

2024-08-12 16:51 UTC, merged